# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'MerryMaids' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MerryMaids
  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'MerryMaids-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'ReactNativeKeyboardManager', :path => '../node_modules/react-native-keyboard-manager'

  end

  target 'MerryMaidsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MerryMaids-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MerryMaids-tvOS

  # target 'MerryMaids-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end
